# Generated by Django 4.2.7 on 2023-12-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('program', models.CharField(max_length=100)),
                ('is_adult', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
