# Generated by Django 4.2.7 on 2023-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
