# Generated by Django 4.2.7 on 2023-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_student_age_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/user_default.jpg', null=True, upload_to='images'),
        ),
    ]
