# Generated by Django 4.2.7 on 2023-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/user2_default.jpg', upload_to='images'),
        ),
    ]
