# Generated by Django 4.2.7 on 2023-12-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_student_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
